# Generated by Django 2.2 on 2023-08-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('BlogImages', models.FileField(upload_to='blogimg')),
                ('Category', models.CharField(max_length=250)),
                ('Summary', models.CharField(max_length=1000)),
                ('Content', models.CharField(max_length=1000)),
                ('IsDraft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ProfilePicture', models.FileField(upload_to='profilepicture')),
                ('UserName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('UserType', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('ConfirmPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
