# Generated by Django 2.2 on 2023-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230823_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='UserID',
            new_name='DoctorID',
        ),
        migrations.AddField(
            model_name='appointment',
            name='PatientID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
