# Generated by Django 2.2 on 2023-08-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230823_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='AppointEnd',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
